### PR TITLE
Re-enable OSG 23 development images (SOFTWARE-5673)

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Review by matyasselmeci — APPROVED** [review]

**Comment by matyasselmeci** [comment]
LGTM; once pelican-osdf-compat is in the htcondor 23.x daily repos (and therefore osg-23-upcoming-development repos) then you should rerun that failed job and merge.

**Comment by matyasselmeci** [comment]
Brian, if this PR is still relevant, can you rerun the jobs and merge if they pass?

**Comment by brianhlin** [comment]
I couldn't find a button to rerun tests for CI this old so I pushed a dummy commit then removed it and force pushed

**Comment by matyasselmeci** [comment]
Possibly #171 fixes this. Brian, can you rebase on master and try again?

**Comment by matyasselmeci** [comment]
I see the problem. I was expecting 23.10.0 to fix the issue and wrote the version comparison accordingly (>=23.8.0, <23.10.0), but the daily is technically called 23.10.0 and doesn't yet fix it.

**Pull request merged**
