### PR TITLE
Moved image to EL8

### PR DESCRIPTION
**Pull request by rynge**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Looks like you'll have to replace "python" commands with "python3" commands.

**Comment by matyasselmeci** [comment]
Alternatively you could stick
```
alternatives --set python /usr/bin/python3
```
to make unversioned python call python3 instead.

**Comment by rynge** [comment]
Committed a fix for the Python issue.

Another "problem" might be that cvmfsexec is based on OSG 3.5. Do you know if there are any plans on moving it to 3.6?

**Comment by matyasselmeci** [comment]
This should do it: https://github.com/cvmfs/cvmfsexec/pull/42

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
