### PR TITLE
Fix singularity detection; add CI tests (SOFTWARE-4725, SOFTWARE-4726)

### PR DESCRIPTION
**Pull request by brianhlin**
Includes #28 and adds tests to verify startd startup and correct values for `HAS_SINGULARITY` for the Docker CVMFS bindmount and cvmfsexec cases

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Can you elaborate on why you copied a bunch of gwms stuff into 10-start-condor.sh?

**Comment by matyasselmeci** [comment]
If you absolutely need this new code, consider putting it in a separate file, such as 09-gwms-whateverthisdoes.sh

**Comment by brianhlin** [comment]
That's all @rynge so I'll let him speak to his changes

**Comment by matyasselmeci** [comment]
Are some of the commits still from #28, or have you rebased them or something? If possible, I'd like to review and merge #28 separately.

**Comment by brianhlin** [comment]
Yeah, feel free to review #28 separately. I'd like to run the tests on any changes, though, so I'll update this PR as appropriate.

**Comment by brianhlin** [comment]
Superseded by #32

**Pull request closed without merging**
