### PR TITLE
skip cuda development and testing builds, they're super slow

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
also, do we have to do both el8 and al8?  is it time to switch over?

**Review by brianhlin — APPROVED** [review]
LGTM. 

> also, do we have to do both el8 and al8? is it time to switch over?

I think we just need to verify that the al8 image works fine and then we can point the el8 tag at al8 and drop the al8 tag. Thoughts on a good instance that'll actually get jobs?

**Comment by matyasselmeci** [comment]
Apparently we already thought we switched in #121 .

**Comment by matyasselmeci** [comment]
Hm. The Singularity+CVMFS bindmount test failed on the cuda-based images because the runner ran out of disk space converting the docker image to a SIF.  This is not the first time I've seen that happen; perhaps we need to skip that test.

**Comment by brianhlin** [comment]
> Apparently we already thought we switched in https://github.com/opensciencegrid/osgvo-docker-pilot/pull/121 .

Yeah, I think that just changed the default in the build but not the default OS in the OS-less tags:

```
lin@blin-work:~$ podman run --rm -it hub.opensciencegrid.org/opensciencegrid/osgvo-docker-pilot:3.6-release cat /etc/os-release
No CVMFS repos requested, skipping cvmfsexec.
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
blin@blin-work:~$ podman run --rm -it hub.opensciencegrid.org/opensciencegrid/osgvo-docker-pilot:3.6-al8-release cat /etc/os-release
No CVMFS repos requested, skipping cvmfsexec.
NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```

I don't suppose you remember exactly what you tested as part of https://opensciencegrid.atlassian.net/browse/SOFTWARE-5452?

**Comment by matyasselmeci** [comment]
> I don't suppose you remember exactly what you tested as part of https://opensciencegrid.atlassian.net/browse/SOFTWARE-5452?

Uh. Running jobs? That might have been the time I added my laptop to the OS Pool...

**Comment by brianhlin** [comment]
> Uh. Running jobs? That might have been the time I added my laptop to the OS Pool...

Lol I meant which tags you tested. If you tested `3.6-release` thinking it was AL8 then we should probably test again

**Comment by matyasselmeci** [comment]
Well I tested AL8 _before_ making it the default so hopefully I was explicit! :)

There's a reasonable chance that I made a local build with the right arguments and tested that.

**Pull request merged**
