### PR TITLE
Relax GPU start/rank expressions so that a container will run jobs ev…

### PR DESCRIPTION
**Pull request by rynge**
…en if there are no GPU jobs in the pool, but still prefer GPU jobs if available

### CODE REVIEW

**Review by matyasselmeci — APPROVED** [review]
LGTM.

**Comment by dsschult** [comment]
I personally dislike this policy, since it's very likely for CPU jobs to steal all the GPUs in a pool, and then they won't be available when a GPU job comes along.  At least, we tried this initially with IceCube's private pool, and quickly moved to reserve a core for each GPU and only run GPU jobs on those.

**Comment by matyasselmeci** [comment]
Can we add preemption of CPU jobs by GPU jobs perhaps?

**Comment by rynge** [comment]
Preemption is certainly a solution - I think it might be disabled pool wide of the OSPool, but I'm happy to work on that bit. 

Another solution would be to create a flag the admin can set to control which behavior they prefer.

Yet another option would be to have "flavors" of the image, that is different tags for the different behaviors. I think this would be confusing. I would lean towards the flag shortterm, and the preemption longterm.

**Comment by dsschult** [comment]
> I would lean towards the flag shortterm, and the preemption longterm.

I'd agree to that.

**Comment by rynge** [comment]
Ok, I will make a new PR

**Comment by bbockelm** [comment]
One trick we have used before is to have the slot go to CPU jobs only if the GPU has remained idle for 15 minutes.

**Pull request closed without merging**
