### PR TITLE
Update the README with instructions for using the /pilot dir

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by brianhlin** [comment]
Should we just remove the README documentation now that we have https://opensciencegrid.org/docs/resource-sharing/os-backfill-containers/ and https://opensciencegrid.org/docs/resource-sharing/user-containers/?

**Comment by matyasselmeci** [comment]
Dunno. I'm adding more stuff to the README in another PR (the cvmfsexec PR). Note that this is the text that shows up on the Docker Hub page for the container.

**Comment by brianhlin** [comment]
> Note that this is the text that shows up on the Docker Hub page for the container.

Huh...how? If that's the case, we should replace the contents of the README with the links to our docs

**Comment by matyasselmeci** [comment]
How about we merge this so it's correct for now, and then we can move the contents to the other doc later (at the next doc focus, perhaps)?

**Comment by matyasselmeci** [comment]
(The README here and the other doc are somewhat different so they will take some time to merge; I already updated the singularity instructions in the other doc but I'd rather not have wrong instructions here, even in the short term.)

**Comment by brianhlin** [comment]
As long as the other docs have the new invocation then that works for me

**Comment by matyasselmeci** [comment]
Yep, updated.

**Pull request merged**
